### PR TITLE
New York Time Sample Page

### PR DESCRIPTION
**Pull request by uzorjchibuzor**
We are applying the positioning and floating lessons learned.  @talihomz

### CODE REVIEW

**Review by talihomz — COMMENTED** [review]
@uzorjchibuzor @MrObele, great work on this!

Some suggestions:
1. The navbar size can be improved to match that of NY Times
2. Try make the page responsive ;-)

Lastly, please improve on the README file.

**Comment by MrObele** [comment]
@talihomz , Thanks for your suggestions and corrections.
The above issues have been worked on and the readme file updated as well.

**Comment by uzorjchibuzor** [comment]
Link to Review GuideLines  `https://docs.google.com/document/d/1JrKsYPS_t_QOTUm927UIk-e1ZiqZeaTfNufq-P0DxCE/edit`

**Comment by talihomz** [comment]
Great job with this guys! 

I noticed a hack on the 'Theory of Inflation' section. This works well on desktop, but you would have to find a way to display it on mobile.

Its a :+1: from me.

**Comment by uzorjchibuzor** [comment]
@talihomz  Many of the issues we had was that we made sure not to use bootstrap in any of those projects until we got to the bootstrap section. We learnt a lot along the way. Thank you for all the help.

I will merge this now.

**Pull request merged**
